pipeline {
    agent {
        dockerfile {
            dir '.ci'
            label 'docker-executor'
        }
    }

    stages {
        stage('Install') {
            steps {
                sh 'sudo make bootstrap'
            }
        }
        stage('Test') {
            parallel {
                stage('Lint') {
                    steps {
                        sh 'make lint'
                    }
                }
                stage('Unit') {
                    steps {
                        sh 'make test'
                    }
                }
            }
        }
    }
}
